name: Testing with unit tests

on:
  - push
  - pull_request

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: tarantool/setup-tarantool@v3
      with:
        tarantool-version: '2.11.2'
    - name: run tests
      run: make test
    - name: publish coveralls report
      if: github.event_name != 'pull_request'
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: .rocks/bin/luacov-coveralls -v
    - name: run benchmarks
      run: make bench
